# Generated by Django 2.2.5 on 2020-03-01 10:09

from django.db import migrations

def check_if_new_building(apps, schema_editor):
    earliest_new_building_year = 2015
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= earliest_new_building_year
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
            migrations.RunPython(check_if_new_building),
    ]