# Generated by Django 2.2.5 on 2020-03-01 11:42

from django.db import migrations

import phonenumbers

def standardize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    country_code = "RU"
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, country_code)
        flat.owner_phone_pure = phonenumbers.format_number(
                parsed_phonenumber, phonenumbers.PhoneNumberFormat.E164
                ) if phonenumbers.is_valid_number(parsed_phonenumber) else ""
        flat.save()

def move_backwards(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ""
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
            migrations.RunPython(standardize_phone_number, move_backwards),
    ]